# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import indrive_client
from indrive_client.api.callbacks_api import CallbacksApi  # noqa: E501
from indrive_client.rest import ApiException


class TestCallbacksApi(unittest.TestCase):
    """CallbacksApi unit test stubs"""

    def setUp(self):
        self.api = CallbacksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_merchant_courier_near_delivery_address_callback_url_order_id_post(self):
        """Test case for merchant_courier_near_delivery_address_callback_url_order_id_post

        The rider is near the delivery address callback  # noqa: E501
        """
        pass

    def test_merchant_courier_near_place_callback_url_order_id_post(self):
        """Test case for merchant_courier_near_place_callback_url_order_id_post

        The rider is near the pickup place callback  # noqa: E501
        """
        pass

    def test_merchant_order_status_callback_url_order_id_post(self):
        """Test case for merchant_order_status_callback_url_order_id_post

        The order changed callback  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
