# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import indrive_client
from indrive_client.api.orders_api import OrdersApi  # noqa: E501
from indrive_client.rest import ApiException


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self):
        self.api = OrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_public_cancel_order_public_v1_orders_order_id_delete(self):
        """Test case for public_cancel_order_public_v1_orders_order_id_delete

        Public:Cancel Order  # noqa: E501
        """
        pass

    def test_public_create_order_public_v1_orders_post(self):
        """Test case for public_create_order_public_v1_orders_post

        Public:Create Order  # noqa: E501
        """
        pass

    def test_public_dry_run_public_v1_orders_dry_run_post(self):
        """Test case for public_dry_run_public_v1_orders_dry_run_post

        Public:Dry Run  # noqa: E501
        """
        pass

    def test_public_get_courier_position_public_v1_orders_order_id_tracking_get(self):
        """Test case for public_get_courier_position_public_v1_orders_order_id_tracking_get

        Public:Get Courier Position  # noqa: E501
        """
        pass

    def test_public_get_order_photos_public_v1_orders_order_id_photos_get(self):
        """Test case for public_get_order_photos_public_v1_orders_order_id_photos_get

        Public:Get Order Photos  # noqa: E501
        """
        pass

    def test_public_get_order_public_v1_orders_order_id_get(self):
        """Test case for public_get_order_public_v1_orders_order_id_get

        Public:Get Order  # noqa: E501
        """
        pass

    def test_public_return_order_public_v1_orders_order_id_return_patch(self):
        """Test case for public_return_order_public_v1_orders_order_id_return_patch

        Public:Return Order  # noqa: E501
        """
        pass

    def test_public_return_order_public_v2_orders_order_id_return_patch(self):
        """Test case for public_return_order_public_v2_orders_order_id_return_patch

        Public:Return Order  # noqa: E501
        """
        pass

    def test_public_update_order_public_v1_orders_order_id_patch(self):
        """Test case for public_update_order_public_v1_orders_order_id_patch

        Public:Update Order  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
