# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import indrive_client
from indrive_client.models.area_create_without_place import AreaCreateWithoutPlace  # noqa: E501
from indrive_client.rest import ApiException


class TestAreaCreateWithoutPlace(unittest.TestCase):
    """AreaCreateWithoutPlace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAreaCreateWithoutPlace(self):
        """Test AreaCreateWithoutPlace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = indrive_client.models.area_create_without_place.AreaCreateWithoutPlace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
