# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import indrive_client
from indrive_client.models.public_delivery_for_response_v11 import PublicDeliveryForResponseV11  # noqa: E501
from indrive_client.rest import ApiException


class TestPublicDeliveryForResponseV11(unittest.TestCase):
    """PublicDeliveryForResponseV11 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPublicDeliveryForResponseV11(self):
        """Test PublicDeliveryForResponseV11"""
        # FIXME: construct object with mandatory attributes with example values
        # model = indrive_client.models.public_delivery_for_response_v11.PublicDeliveryForResponseV11()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
