# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import indrive_client
from indrive_client.api.places_api import PlacesApi  # noqa: E501
from indrive_client.rest import ApiException


class TestPlacesApi(unittest.TestCase):
    """PlacesApi unit test stubs"""

    def setUp(self):
        self.api = PlacesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_place_schedule_get_public_v1_merchant_places_place_id_schedule_get(self):
        """Test case for place_schedule_get_public_v1_merchant_places_place_id_schedule_get

        Place Schedule:Get  # noqa: E501
        """
        pass

    def test_place_schedule_update_public_v1_merchant_places_place_id_schedule_put(self):
        """Test case for place_schedule_update_public_v1_merchant_places_place_id_schedule_put

        Place Schedule:Update  # noqa: E501
        """
        pass

    def test_places_block_public_v1_merchant_places_block_post(self):
        """Test case for places_block_public_v1_merchant_places_block_post

        Places:Block  # noqa: E501
        """
        pass

    def test_places_blocks_public_v1_merchant_places_blocks_get(self):
        """Test case for places_blocks_public_v1_merchant_places_blocks_get

        Places:Blocks  # noqa: E501
        """
        pass

    def test_places_create_public_v1_merchant_places_post(self):
        """Test case for places_create_public_v1_merchant_places_post

        Places:Create  # noqa: E501
        """
        pass

    def test_places_list_public_v1_merchant_places_get(self):
        """Test case for places_list_public_v1_merchant_places_get

        Places:List  # noqa: E501
        """
        pass

    def test_places_order_check_public_v1_merchant_places_order_check_post(self):
        """Test case for places_order_check_public_v1_merchant_places_order_check_post

        Places:Order Check  # noqa: E501
        """
        pass

    def test_places_unblock_public_v1_merchant_places_unblock_post(self):
        """Test case for places_unblock_public_v1_merchant_places_unblock_post

        Places:Unblock  # noqa: E501
        """
        pass

    def test_places_update_public_v1_merchant_places_place_id_put(self):
        """Test case for places_update_public_v1_merchant_places_place_id_put

        Places:Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
