# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import indrive_client
from indrive_client.models.place_with_area import PlaceWithArea  # noqa: E501
from indrive_client.rest import ApiException


class TestPlaceWithArea(unittest.TestCase):
    """PlaceWithArea unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlaceWithArea(self):
        """Test PlaceWithArea"""
        # FIXME: construct object with mandatory attributes with example values
        # model = indrive_client.models.place_with_area.PlaceWithArea()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
