# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import indrive_client
from indrive_client.models.delivery_dry_run_in_request import DeliveryDryRunInRequest  # noqa: E501
from indrive_client.rest import ApiException


class TestDeliveryDryRunInRequest(unittest.TestCase):
    """DeliveryDryRunInRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeliveryDryRunInRequest(self):
        """Test DeliveryDryRunInRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = indrive_client.models.delivery_dry_run_in_request.DeliveryDryRunInRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
