# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import indrive_client
from indrive_client.models.create_order_in_request_v11 import CreateOrderInRequestV11  # noqa: E501
from indrive_client.rest import ApiException


class TestCreateOrderInRequestV11(unittest.TestCase):
    """CreateOrderInRequestV11 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateOrderInRequestV11(self):
        """Test CreateOrderInRequestV11"""
        # FIXME: construct object with mandatory attributes with example values
        # model = indrive_client.models.create_order_in_request_v11.CreateOrderInRequestV11()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
