# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import indrive_client
from indrive_client.models.work_times import WorkTimes  # noqa: E501
from indrive_client.rest import ApiException


class TestWorkTimes(unittest.TestCase):
    """WorkTimes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkTimes(self):
        """Test WorkTimes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = indrive_client.models.work_times.WorkTimes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
