# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import indrive_client
from indrive_client.models.product_for_response import ProductForResponse  # noqa: E501
from indrive_client.rest import ApiException


class TestProductForResponse(unittest.TestCase):
    """ProductForResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductForResponse(self):
        """Test ProductForResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = indrive_client.models.product_for_response.ProductForResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
