# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import indrive_client
from indrive_client.api.merchant_api import MerchantApi  # noqa: E501
from indrive_client.rest import ApiException


class TestMerchantApi(unittest.TestCase):
    """MerchantApi unit test stubs"""

    def setUp(self):
        self.api = MerchantApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_merchant_schedule_get_public_v1_merchant_merchant_id_schedule_get(self):
        """Test case for merchant_schedule_get_public_v1_merchant_merchant_id_schedule_get

        Merchant Schedule:Get  # noqa: E501
        """
        pass

    def test_merchant_schedule_update_public_v1_merchant_merchant_id_schedule_put(self):
        """Test case for merchant_schedule_update_public_v1_merchant_merchant_id_schedule_put

        Merchant Schedule:Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
