# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AreaCreateWithoutPlace(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'min_delivery_duration': 'int',
        'max_delivery_duration': 'int',
        'geometry': 'AllOfAreaCreateWithoutPlaceGeometry'
    }

    attribute_map = {
        'min_delivery_duration': 'min_delivery_duration',
        'max_delivery_duration': 'max_delivery_duration',
        'geometry': 'geometry'
    }

    def __init__(self, min_delivery_duration=None, max_delivery_duration=None, geometry=None):  # noqa: E501
        """AreaCreateWithoutPlace - a model defined in Swagger"""  # noqa: E501
        self._min_delivery_duration = None
        self._max_delivery_duration = None
        self._geometry = None
        self.discriminator = None
        self.min_delivery_duration = min_delivery_duration
        self.max_delivery_duration = max_delivery_duration
        self.geometry = geometry

    @property
    def min_delivery_duration(self):
        """Gets the min_delivery_duration of this AreaCreateWithoutPlace.  # noqa: E501


        :return: The min_delivery_duration of this AreaCreateWithoutPlace.  # noqa: E501
        :rtype: int
        """
        return self._min_delivery_duration

    @min_delivery_duration.setter
    def min_delivery_duration(self, min_delivery_duration):
        """Sets the min_delivery_duration of this AreaCreateWithoutPlace.


        :param min_delivery_duration: The min_delivery_duration of this AreaCreateWithoutPlace.  # noqa: E501
        :type: int
        """
        if min_delivery_duration is None:
            raise ValueError("Invalid value for `min_delivery_duration`, must not be `None`")  # noqa: E501

        self._min_delivery_duration = min_delivery_duration

    @property
    def max_delivery_duration(self):
        """Gets the max_delivery_duration of this AreaCreateWithoutPlace.  # noqa: E501


        :return: The max_delivery_duration of this AreaCreateWithoutPlace.  # noqa: E501
        :rtype: int
        """
        return self._max_delivery_duration

    @max_delivery_duration.setter
    def max_delivery_duration(self, max_delivery_duration):
        """Sets the max_delivery_duration of this AreaCreateWithoutPlace.


        :param max_delivery_duration: The max_delivery_duration of this AreaCreateWithoutPlace.  # noqa: E501
        :type: int
        """
        if max_delivery_duration is None:
            raise ValueError("Invalid value for `max_delivery_duration`, must not be `None`")  # noqa: E501

        self._max_delivery_duration = max_delivery_duration

    @property
    def geometry(self):
        """Gets the geometry of this AreaCreateWithoutPlace.  # noqa: E501

        kml as geojson  # noqa: E501

        :return: The geometry of this AreaCreateWithoutPlace.  # noqa: E501
        :rtype: AllOfAreaCreateWithoutPlaceGeometry
        """
        return self._geometry

    @geometry.setter
    def geometry(self, geometry):
        """Sets the geometry of this AreaCreateWithoutPlace.

        kml as geojson  # noqa: E501

        :param geometry: The geometry of this AreaCreateWithoutPlace.  # noqa: E501
        :type: AllOfAreaCreateWithoutPlaceGeometry
        """
        if geometry is None:
            raise ValueError("Invalid value for `geometry`, must not be `None`")  # noqa: E501

        self._geometry = geometry

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AreaCreateWithoutPlace, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AreaCreateWithoutPlace):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
