# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeliveryExpectedPeriod(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time_from': 'datetime',
        'time_to': 'datetime'
    }

    attribute_map = {
        'time_from': 'time_from',
        'time_to': 'time_to'
    }

    def __init__(self, time_from=None, time_to=None):  # noqa: E501
        """DeliveryExpectedPeriod - a model defined in Swagger"""  # noqa: E501
        self._time_from = None
        self._time_to = None
        self.discriminator = None
        if time_from is not None:
            self.time_from = time_from
        if time_to is not None:
            self.time_to = time_to

    @property
    def time_from(self):
        """Gets the time_from of this DeliveryExpectedPeriod.  # noqa: E501


        :return: The time_from of this DeliveryExpectedPeriod.  # noqa: E501
        :rtype: datetime
        """
        return self._time_from

    @time_from.setter
    def time_from(self, time_from):
        """Sets the time_from of this DeliveryExpectedPeriod.


        :param time_from: The time_from of this DeliveryExpectedPeriod.  # noqa: E501
        :type: datetime
        """

        self._time_from = time_from

    @property
    def time_to(self):
        """Gets the time_to of this DeliveryExpectedPeriod.  # noqa: E501


        :return: The time_to of this DeliveryExpectedPeriod.  # noqa: E501
        :rtype: datetime
        """
        return self._time_to

    @time_to.setter
    def time_to(self, time_to):
        """Sets the time_to of this DeliveryExpectedPeriod.


        :param time_to: The time_to of this DeliveryExpectedPeriod.  # noqa: E501
        :type: datetime
        """

        self._time_to = time_to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeliveryExpectedPeriod, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeliveryExpectedPeriod):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
