# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeliveryAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'short_code': 'str',
        'pin_code': 'str',
        'channel': 'str',
        'bank_transaction_id': 'str'
    }

    attribute_map = {
        'short_code': 'short_code',
        'pin_code': 'pin_code',
        'channel': 'channel',
        'bank_transaction_id': 'bank_transaction_id'
    }

    def __init__(self, short_code=None, pin_code=None, channel=None, bank_transaction_id=None):  # noqa: E501
        """DeliveryAttributes - a model defined in Swagger"""  # noqa: E501
        self._short_code = None
        self._pin_code = None
        self._channel = None
        self._bank_transaction_id = None
        self.discriminator = None
        if short_code is not None:
            self.short_code = short_code
        if pin_code is not None:
            self.pin_code = pin_code
        if channel is not None:
            self.channel = channel
        if bank_transaction_id is not None:
            self.bank_transaction_id = bank_transaction_id

    @property
    def short_code(self):
        """Gets the short_code of this DeliveryAttributes.  # noqa: E501


        :return: The short_code of this DeliveryAttributes.  # noqa: E501
        :rtype: str
        """
        return self._short_code

    @short_code.setter
    def short_code(self, short_code):
        """Sets the short_code of this DeliveryAttributes.


        :param short_code: The short_code of this DeliveryAttributes.  # noqa: E501
        :type: str
        """

        self._short_code = short_code

    @property
    def pin_code(self):
        """Gets the pin_code of this DeliveryAttributes.  # noqa: E501


        :return: The pin_code of this DeliveryAttributes.  # noqa: E501
        :rtype: str
        """
        return self._pin_code

    @pin_code.setter
    def pin_code(self, pin_code):
        """Sets the pin_code of this DeliveryAttributes.


        :param pin_code: The pin_code of this DeliveryAttributes.  # noqa: E501
        :type: str
        """

        self._pin_code = pin_code

    @property
    def channel(self):
        """Gets the channel of this DeliveryAttributes.  # noqa: E501


        :return: The channel of this DeliveryAttributes.  # noqa: E501
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this DeliveryAttributes.


        :param channel: The channel of this DeliveryAttributes.  # noqa: E501
        :type: str
        """

        self._channel = channel

    @property
    def bank_transaction_id(self):
        """Gets the bank_transaction_id of this DeliveryAttributes.  # noqa: E501


        :return: The bank_transaction_id of this DeliveryAttributes.  # noqa: E501
        :rtype: str
        """
        return self._bank_transaction_id

    @bank_transaction_id.setter
    def bank_transaction_id(self, bank_transaction_id):
        """Sets the bank_transaction_id of this DeliveryAttributes.


        :param bank_transaction_id: The bank_transaction_id of this DeliveryAttributes.  # noqa: E501
        :type: str
        """

        self._bank_transaction_id = bank_transaction_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeliveryAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeliveryAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
