# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrderStatusCallback(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'float',
        'cancel_code': 'float',
        'cancel_reason': 'str',
        'delivery_expected_time': 'datetime',
        'photos': 'list[OrderStatusCallbackPhotos]'
    }

    attribute_map = {
        'status': 'status',
        'cancel_code': 'cancel_code',
        'cancel_reason': 'cancel_reason',
        'delivery_expected_time': 'delivery_expected_time',
        'photos': 'photos'
    }

    def __init__(self, status=None, cancel_code=None, cancel_reason=None, delivery_expected_time=None, photos=None):  # noqa: E501
        """OrderStatusCallback - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._cancel_code = None
        self._cancel_reason = None
        self._delivery_expected_time = None
        self._photos = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if cancel_code is not None:
            self.cancel_code = cancel_code
        if cancel_reason is not None:
            self.cancel_reason = cancel_reason
        if delivery_expected_time is not None:
            self.delivery_expected_time = delivery_expected_time
        if photos is not None:
            self.photos = photos

    @property
    def status(self):
        """Gets the status of this OrderStatusCallback.  # noqa: E501


        :return: The status of this OrderStatusCallback.  # noqa: E501
        :rtype: float
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this OrderStatusCallback.


        :param status: The status of this OrderStatusCallback.  # noqa: E501
        :type: float
        """

        self._status = status

    @property
    def cancel_code(self):
        """Gets the cancel_code of this OrderStatusCallback.  # noqa: E501


        :return: The cancel_code of this OrderStatusCallback.  # noqa: E501
        :rtype: float
        """
        return self._cancel_code

    @cancel_code.setter
    def cancel_code(self, cancel_code):
        """Sets the cancel_code of this OrderStatusCallback.


        :param cancel_code: The cancel_code of this OrderStatusCallback.  # noqa: E501
        :type: float
        """

        self._cancel_code = cancel_code

    @property
    def cancel_reason(self):
        """Gets the cancel_reason of this OrderStatusCallback.  # noqa: E501


        :return: The cancel_reason of this OrderStatusCallback.  # noqa: E501
        :rtype: str
        """
        return self._cancel_reason

    @cancel_reason.setter
    def cancel_reason(self, cancel_reason):
        """Sets the cancel_reason of this OrderStatusCallback.


        :param cancel_reason: The cancel_reason of this OrderStatusCallback.  # noqa: E501
        :type: str
        """

        self._cancel_reason = cancel_reason

    @property
    def delivery_expected_time(self):
        """Gets the delivery_expected_time of this OrderStatusCallback.  # noqa: E501


        :return: The delivery_expected_time of this OrderStatusCallback.  # noqa: E501
        :rtype: datetime
        """
        return self._delivery_expected_time

    @delivery_expected_time.setter
    def delivery_expected_time(self, delivery_expected_time):
        """Sets the delivery_expected_time of this OrderStatusCallback.


        :param delivery_expected_time: The delivery_expected_time of this OrderStatusCallback.  # noqa: E501
        :type: datetime
        """

        self._delivery_expected_time = delivery_expected_time

    @property
    def photos(self):
        """Gets the photos of this OrderStatusCallback.  # noqa: E501


        :return: The photos of this OrderStatusCallback.  # noqa: E501
        :rtype: list[OrderStatusCallbackPhotos]
        """
        return self._photos

    @photos.setter
    def photos(self, photos):
        """Sets the photos of this OrderStatusCallback.


        :param photos: The photos of this OrderStatusCallback.  # noqa: E501
        :type: list[OrderStatusCallbackPhotos]
        """

        self._photos = photos

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderStatusCallback, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderStatusCallback):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
