# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrderStatusCallbackPhotos(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'url': 'str',
        'photo_type': 'float'
    }

    attribute_map = {
        'id': 'id',
        'url': 'url',
        'photo_type': 'photo_type'
    }

    def __init__(self, id=None, url=None, photo_type=None):  # noqa: E501
        """OrderStatusCallbackPhotos - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._url = None
        self._photo_type = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if url is not None:
            self.url = url
        if photo_type is not None:
            self.photo_type = photo_type

    @property
    def id(self):
        """Gets the id of this OrderStatusCallbackPhotos.  # noqa: E501


        :return: The id of this OrderStatusCallbackPhotos.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OrderStatusCallbackPhotos.


        :param id: The id of this OrderStatusCallbackPhotos.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def url(self):
        """Gets the url of this OrderStatusCallbackPhotos.  # noqa: E501


        :return: The url of this OrderStatusCallbackPhotos.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this OrderStatusCallbackPhotos.


        :param url: The url of this OrderStatusCallbackPhotos.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def photo_type(self):
        """Gets the photo_type of this OrderStatusCallbackPhotos.  # noqa: E501

        1 - the courier received the order, 2 - the coureir delivered the order  # noqa: E501

        :return: The photo_type of this OrderStatusCallbackPhotos.  # noqa: E501
        :rtype: float
        """
        return self._photo_type

    @photo_type.setter
    def photo_type(self, photo_type):
        """Sets the photo_type of this OrderStatusCallbackPhotos.

        1 - the courier received the order, 2 - the coureir delivered the order  # noqa: E501

        :param photo_type: The photo_type of this OrderStatusCallbackPhotos.  # noqa: E501
        :type: float
        """
        allowed_values = [1, 2]  # noqa: E501
        if photo_type not in allowed_values:
            raise ValueError(
                "Invalid value for `photo_type` ({0}), must be one of {1}"  # noqa: E501
                .format(photo_type, allowed_values)
            )

        self._photo_type = photo_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderStatusCallbackPhotos, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderStatusCallbackPhotos):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
