# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrderPhotoForResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'photo_url': 'str',
        'photo_type': 'OrderPhotoType',
        'created_at': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'photo_url': 'photo_url',
        'photo_type': 'photo_type',
        'created_at': 'created_at'
    }

    def __init__(self, id=None, photo_url=None, photo_type=None, created_at=None):  # noqa: E501
        """OrderPhotoForResponse - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._photo_url = None
        self._photo_type = None
        self._created_at = None
        self.discriminator = None
        self.id = id
        self.photo_url = photo_url
        self.photo_type = photo_type
        self.created_at = created_at

    @property
    def id(self):
        """Gets the id of this OrderPhotoForResponse.  # noqa: E501


        :return: The id of this OrderPhotoForResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OrderPhotoForResponse.


        :param id: The id of this OrderPhotoForResponse.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def photo_url(self):
        """Gets the photo_url of this OrderPhotoForResponse.  # noqa: E501


        :return: The photo_url of this OrderPhotoForResponse.  # noqa: E501
        :rtype: str
        """
        return self._photo_url

    @photo_url.setter
    def photo_url(self, photo_url):
        """Sets the photo_url of this OrderPhotoForResponse.


        :param photo_url: The photo_url of this OrderPhotoForResponse.  # noqa: E501
        :type: str
        """
        if photo_url is None:
            raise ValueError("Invalid value for `photo_url`, must not be `None`")  # noqa: E501

        self._photo_url = photo_url

    @property
    def photo_type(self):
        """Gets the photo_type of this OrderPhotoForResponse.  # noqa: E501


        :return: The photo_type of this OrderPhotoForResponse.  # noqa: E501
        :rtype: OrderPhotoType
        """
        return self._photo_type

    @photo_type.setter
    def photo_type(self, photo_type):
        """Sets the photo_type of this OrderPhotoForResponse.


        :param photo_type: The photo_type of this OrderPhotoForResponse.  # noqa: E501
        :type: OrderPhotoType
        """
        if photo_type is None:
            raise ValueError("Invalid value for `photo_type`, must not be `None`")  # noqa: E501

        self._photo_type = photo_type

    @property
    def created_at(self):
        """Gets the created_at of this OrderPhotoForResponse.  # noqa: E501


        :return: The created_at of this OrderPhotoForResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this OrderPhotoForResponse.


        :param created_at: The created_at of this OrderPhotoForResponse.  # noqa: E501
        :type: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderPhotoForResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderPhotoForResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
