# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlaceUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'location': 'DbModelsBasePoint',
        'address': 'str',
        'name': 'str',
        'city_id': 'int',
        'email': 'str',
        'merchant_place_id': 'str'
    }

    attribute_map = {
        'location': 'location',
        'address': 'address',
        'name': 'name',
        'city_id': 'city_id',
        'email': 'email',
        'merchant_place_id': 'merchant_place_id'
    }

    def __init__(self, location=None, address=None, name=None, city_id=None, email=None, merchant_place_id=None):  # noqa: E501
        """PlaceUpdate - a model defined in Swagger"""  # noqa: E501
        self._location = None
        self._address = None
        self._name = None
        self._city_id = None
        self._email = None
        self._merchant_place_id = None
        self.discriminator = None
        if location is not None:
            self.location = location
        if address is not None:
            self.address = address
        if name is not None:
            self.name = name
        if city_id is not None:
            self.city_id = city_id
        if email is not None:
            self.email = email
        if merchant_place_id is not None:
            self.merchant_place_id = merchant_place_id

    @property
    def location(self):
        """Gets the location of this PlaceUpdate.  # noqa: E501


        :return: The location of this PlaceUpdate.  # noqa: E501
        :rtype: DbModelsBasePoint
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this PlaceUpdate.


        :param location: The location of this PlaceUpdate.  # noqa: E501
        :type: DbModelsBasePoint
        """

        self._location = location

    @property
    def address(self):
        """Gets the address of this PlaceUpdate.  # noqa: E501


        :return: The address of this PlaceUpdate.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this PlaceUpdate.


        :param address: The address of this PlaceUpdate.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def name(self):
        """Gets the name of this PlaceUpdate.  # noqa: E501


        :return: The name of this PlaceUpdate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PlaceUpdate.


        :param name: The name of this PlaceUpdate.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def city_id(self):
        """Gets the city_id of this PlaceUpdate.  # noqa: E501


        :return: The city_id of this PlaceUpdate.  # noqa: E501
        :rtype: int
        """
        return self._city_id

    @city_id.setter
    def city_id(self, city_id):
        """Sets the city_id of this PlaceUpdate.


        :param city_id: The city_id of this PlaceUpdate.  # noqa: E501
        :type: int
        """

        self._city_id = city_id

    @property
    def email(self):
        """Gets the email of this PlaceUpdate.  # noqa: E501


        :return: The email of this PlaceUpdate.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this PlaceUpdate.


        :param email: The email of this PlaceUpdate.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def merchant_place_id(self):
        """Gets the merchant_place_id of this PlaceUpdate.  # noqa: E501


        :return: The merchant_place_id of this PlaceUpdate.  # noqa: E501
        :rtype: str
        """
        return self._merchant_place_id

    @merchant_place_id.setter
    def merchant_place_id(self, merchant_place_id):
        """Sets the merchant_place_id of this PlaceUpdate.


        :param merchant_place_id: The merchant_place_id of this PlaceUpdate.  # noqa: E501
        :type: str
        """

        self._merchant_place_id = merchant_place_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlaceUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlaceUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
