# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlaceUnBlockInRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'place_ids': 'list[str]',
        'block_ids': 'list[str]'
    }

    attribute_map = {
        'place_ids': 'place_ids',
        'block_ids': 'block_ids'
    }

    def __init__(self, place_ids=None, block_ids=None):  # noqa: E501
        """PlaceUnBlockInRequest - a model defined in Swagger"""  # noqa: E501
        self._place_ids = None
        self._block_ids = None
        self.discriminator = None
        if place_ids is not None:
            self.place_ids = place_ids
        if block_ids is not None:
            self.block_ids = block_ids

    @property
    def place_ids(self):
        """Gets the place_ids of this PlaceUnBlockInRequest.  # noqa: E501


        :return: The place_ids of this PlaceUnBlockInRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._place_ids

    @place_ids.setter
    def place_ids(self, place_ids):
        """Sets the place_ids of this PlaceUnBlockInRequest.


        :param place_ids: The place_ids of this PlaceUnBlockInRequest.  # noqa: E501
        :type: list[str]
        """

        self._place_ids = place_ids

    @property
    def block_ids(self):
        """Gets the block_ids of this PlaceUnBlockInRequest.  # noqa: E501


        :return: The block_ids of this PlaceUnBlockInRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._block_ids

    @block_ids.setter
    def block_ids(self, block_ids):
        """Sets the block_ids of this PlaceUnBlockInRequest.


        :param block_ids: The block_ids of this PlaceUnBlockInRequest.  # noqa: E501
        :type: list[str]
        """

        self._block_ids = block_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlaceUnBlockInRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlaceUnBlockInRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
