# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlaceAccessList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_access': 'bool',
        'places': 'list[PlaceAccessForResponse]'
    }

    attribute_map = {
        'is_access': 'is_access',
        'places': 'places'
    }

    def __init__(self, is_access=None, places=None):  # noqa: E501
        """PlaceAccessList - a model defined in Swagger"""  # noqa: E501
        self._is_access = None
        self._places = None
        self.discriminator = None
        self.is_access = is_access
        self.places = places

    @property
    def is_access(self):
        """Gets the is_access of this PlaceAccessList.  # noqa: E501


        :return: The is_access of this PlaceAccessList.  # noqa: E501
        :rtype: bool
        """
        return self._is_access

    @is_access.setter
    def is_access(self, is_access):
        """Sets the is_access of this PlaceAccessList.


        :param is_access: The is_access of this PlaceAccessList.  # noqa: E501
        :type: bool
        """
        if is_access is None:
            raise ValueError("Invalid value for `is_access`, must not be `None`")  # noqa: E501

        self._is_access = is_access

    @property
    def places(self):
        """Gets the places of this PlaceAccessList.  # noqa: E501


        :return: The places of this PlaceAccessList.  # noqa: E501
        :rtype: list[PlaceAccessForResponse]
        """
        return self._places

    @places.setter
    def places(self, places):
        """Sets the places of this PlaceAccessList.


        :param places: The places of this PlaceAccessList.  # noqa: E501
        :type: list[PlaceAccessForResponse]
        """
        if places is None:
            raise ValueError("Invalid value for `places`, must not be `None`")  # noqa: E501

        self._places = places

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlaceAccessList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlaceAccessList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
