# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlaceBlockInResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'place_id': 'str',
        'datetime_from': 'datetime',
        'datetime_to': 'datetime',
        'block_reason': 'str',
        'is_blocked': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'place_id': 'place_id',
        'datetime_from': 'datetime_from',
        'datetime_to': 'datetime_to',
        'block_reason': 'block_reason',
        'is_blocked': 'is_blocked'
    }

    def __init__(self, id=None, place_id=None, datetime_from=None, datetime_to=None, block_reason=None, is_blocked=None):  # noqa: E501
        """PlaceBlockInResponse - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._place_id = None
        self._datetime_from = None
        self._datetime_to = None
        self._block_reason = None
        self._is_blocked = None
        self.discriminator = None
        self.id = id
        self.place_id = place_id
        self.datetime_from = datetime_from
        if datetime_to is not None:
            self.datetime_to = datetime_to
        if block_reason is not None:
            self.block_reason = block_reason
        self.is_blocked = is_blocked

    @property
    def id(self):
        """Gets the id of this PlaceBlockInResponse.  # noqa: E501


        :return: The id of this PlaceBlockInResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PlaceBlockInResponse.


        :param id: The id of this PlaceBlockInResponse.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def place_id(self):
        """Gets the place_id of this PlaceBlockInResponse.  # noqa: E501


        :return: The place_id of this PlaceBlockInResponse.  # noqa: E501
        :rtype: str
        """
        return self._place_id

    @place_id.setter
    def place_id(self, place_id):
        """Sets the place_id of this PlaceBlockInResponse.


        :param place_id: The place_id of this PlaceBlockInResponse.  # noqa: E501
        :type: str
        """
        if place_id is None:
            raise ValueError("Invalid value for `place_id`, must not be `None`")  # noqa: E501

        self._place_id = place_id

    @property
    def datetime_from(self):
        """Gets the datetime_from of this PlaceBlockInResponse.  # noqa: E501


        :return: The datetime_from of this PlaceBlockInResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._datetime_from

    @datetime_from.setter
    def datetime_from(self, datetime_from):
        """Sets the datetime_from of this PlaceBlockInResponse.


        :param datetime_from: The datetime_from of this PlaceBlockInResponse.  # noqa: E501
        :type: datetime
        """
        if datetime_from is None:
            raise ValueError("Invalid value for `datetime_from`, must not be `None`")  # noqa: E501

        self._datetime_from = datetime_from

    @property
    def datetime_to(self):
        """Gets the datetime_to of this PlaceBlockInResponse.  # noqa: E501


        :return: The datetime_to of this PlaceBlockInResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._datetime_to

    @datetime_to.setter
    def datetime_to(self, datetime_to):
        """Sets the datetime_to of this PlaceBlockInResponse.


        :param datetime_to: The datetime_to of this PlaceBlockInResponse.  # noqa: E501
        :type: datetime
        """

        self._datetime_to = datetime_to

    @property
    def block_reason(self):
        """Gets the block_reason of this PlaceBlockInResponse.  # noqa: E501


        :return: The block_reason of this PlaceBlockInResponse.  # noqa: E501
        :rtype: str
        """
        return self._block_reason

    @block_reason.setter
    def block_reason(self, block_reason):
        """Sets the block_reason of this PlaceBlockInResponse.


        :param block_reason: The block_reason of this PlaceBlockInResponse.  # noqa: E501
        :type: str
        """

        self._block_reason = block_reason

    @property
    def is_blocked(self):
        """Gets the is_blocked of this PlaceBlockInResponse.  # noqa: E501


        :return: The is_blocked of this PlaceBlockInResponse.  # noqa: E501
        :rtype: bool
        """
        return self._is_blocked

    @is_blocked.setter
    def is_blocked(self, is_blocked):
        """Sets the is_blocked of this PlaceBlockInResponse.


        :param is_blocked: The is_blocked of this PlaceBlockInResponse.  # noqa: E501
        :type: bool
        """
        if is_blocked is None:
            raise ValueError("Invalid value for `is_blocked`, must not be `None`")  # noqa: E501

        self._is_blocked = is_blocked

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlaceBlockInResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlaceBlockInResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
