# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProductForResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'quantity': 'int',
        'price': 'float',
        'total_price': 'float',
        'vat_code': 'str',
        'external_id': 'str',
        'rkeeper_code': 'str',
        'refund_quantity': 'int',
        'ingredients': 'list[IngredientForResponse]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'quantity': 'quantity',
        'price': 'price',
        'total_price': 'total_price',
        'vat_code': 'vat_code',
        'external_id': 'external_id',
        'rkeeper_code': 'rkeeper_code',
        'refund_quantity': 'refund_quantity',
        'ingredients': 'ingredients'
    }

    def __init__(self, id=None, name=None, quantity=None, price=None, total_price=None, vat_code=None, external_id=None, rkeeper_code=None, refund_quantity=None, ingredients=None):  # noqa: E501
        """ProductForResponse - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._quantity = None
        self._price = None
        self._total_price = None
        self._vat_code = None
        self._external_id = None
        self._rkeeper_code = None
        self._refund_quantity = None
        self._ingredients = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.quantity = quantity
        self.price = price
        self.total_price = total_price
        if vat_code is not None:
            self.vat_code = vat_code
        if external_id is not None:
            self.external_id = external_id
        if rkeeper_code is not None:
            self.rkeeper_code = rkeeper_code
        self.refund_quantity = refund_quantity
        if ingredients is not None:
            self.ingredients = ingredients

    @property
    def id(self):
        """Gets the id of this ProductForResponse.  # noqa: E501


        :return: The id of this ProductForResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ProductForResponse.


        :param id: The id of this ProductForResponse.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this ProductForResponse.  # noqa: E501


        :return: The name of this ProductForResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProductForResponse.


        :param name: The name of this ProductForResponse.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def quantity(self):
        """Gets the quantity of this ProductForResponse.  # noqa: E501


        :return: The quantity of this ProductForResponse.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this ProductForResponse.


        :param quantity: The quantity of this ProductForResponse.  # noqa: E501
        :type: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity

    @property
    def price(self):
        """Gets the price of this ProductForResponse.  # noqa: E501


        :return: The price of this ProductForResponse.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this ProductForResponse.


        :param price: The price of this ProductForResponse.  # noqa: E501
        :type: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def total_price(self):
        """Gets the total_price of this ProductForResponse.  # noqa: E501


        :return: The total_price of this ProductForResponse.  # noqa: E501
        :rtype: float
        """
        return self._total_price

    @total_price.setter
    def total_price(self, total_price):
        """Sets the total_price of this ProductForResponse.


        :param total_price: The total_price of this ProductForResponse.  # noqa: E501
        :type: float
        """
        if total_price is None:
            raise ValueError("Invalid value for `total_price`, must not be `None`")  # noqa: E501

        self._total_price = total_price

    @property
    def vat_code(self):
        """Gets the vat_code of this ProductForResponse.  # noqa: E501


        :return: The vat_code of this ProductForResponse.  # noqa: E501
        :rtype: str
        """
        return self._vat_code

    @vat_code.setter
    def vat_code(self, vat_code):
        """Sets the vat_code of this ProductForResponse.


        :param vat_code: The vat_code of this ProductForResponse.  # noqa: E501
        :type: str
        """

        self._vat_code = vat_code

    @property
    def external_id(self):
        """Gets the external_id of this ProductForResponse.  # noqa: E501


        :return: The external_id of this ProductForResponse.  # noqa: E501
        :rtype: str
        """
        return self._external_id

    @external_id.setter
    def external_id(self, external_id):
        """Sets the external_id of this ProductForResponse.


        :param external_id: The external_id of this ProductForResponse.  # noqa: E501
        :type: str
        """

        self._external_id = external_id

    @property
    def rkeeper_code(self):
        """Gets the rkeeper_code of this ProductForResponse.  # noqa: E501


        :return: The rkeeper_code of this ProductForResponse.  # noqa: E501
        :rtype: str
        """
        return self._rkeeper_code

    @rkeeper_code.setter
    def rkeeper_code(self, rkeeper_code):
        """Sets the rkeeper_code of this ProductForResponse.


        :param rkeeper_code: The rkeeper_code of this ProductForResponse.  # noqa: E501
        :type: str
        """

        self._rkeeper_code = rkeeper_code

    @property
    def refund_quantity(self):
        """Gets the refund_quantity of this ProductForResponse.  # noqa: E501


        :return: The refund_quantity of this ProductForResponse.  # noqa: E501
        :rtype: int
        """
        return self._refund_quantity

    @refund_quantity.setter
    def refund_quantity(self, refund_quantity):
        """Sets the refund_quantity of this ProductForResponse.


        :param refund_quantity: The refund_quantity of this ProductForResponse.  # noqa: E501
        :type: int
        """
        if refund_quantity is None:
            raise ValueError("Invalid value for `refund_quantity`, must not be `None`")  # noqa: E501

        self._refund_quantity = refund_quantity

    @property
    def ingredients(self):
        """Gets the ingredients of this ProductForResponse.  # noqa: E501


        :return: The ingredients of this ProductForResponse.  # noqa: E501
        :rtype: list[IngredientForResponse]
        """
        return self._ingredients

    @ingredients.setter
    def ingredients(self, ingredients):
        """Sets the ingredients of this ProductForResponse.


        :param ingredients: The ingredients of this ProductForResponse.  # noqa: E501
        :type: list[IngredientForResponse]
        """

        self._ingredients = ingredients

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductForResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductForResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
