# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ReturnProductsInRequestV2(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'products': 'list[ReturnProductsInRequestV2Products]',
        'return_amount': 'float',
        'new_total_amount': 'float',
        'reason': 'str',
        'cancel_code': 'OrderCancelCodeEnum'
    }

    attribute_map = {
        'products': 'products',
        'return_amount': 'return_amount',
        'new_total_amount': 'new_total_amount',
        'reason': 'reason',
        'cancel_code': 'cancel_code'
    }

    def __init__(self, products=None, return_amount=None, new_total_amount=None, reason=None, cancel_code=None):  # noqa: E501
        """ReturnProductsInRequestV2 - a model defined in Swagger"""  # noqa: E501
        self._products = None
        self._return_amount = None
        self._new_total_amount = None
        self._reason = None
        self._cancel_code = None
        self.discriminator = None
        self.products = products
        self.return_amount = return_amount
        self.new_total_amount = new_total_amount
        self.reason = reason
        if cancel_code is not None:
            self.cancel_code = cancel_code

    @property
    def products(self):
        """Gets the products of this ReturnProductsInRequestV2.  # noqa: E501


        :return: The products of this ReturnProductsInRequestV2.  # noqa: E501
        :rtype: list[ReturnProductsInRequestV2Products]
        """
        return self._products

    @products.setter
    def products(self, products):
        """Sets the products of this ReturnProductsInRequestV2.


        :param products: The products of this ReturnProductsInRequestV2.  # noqa: E501
        :type: list[ReturnProductsInRequestV2Products]
        """
        if products is None:
            raise ValueError("Invalid value for `products`, must not be `None`")  # noqa: E501

        self._products = products

    @property
    def return_amount(self):
        """Gets the return_amount of this ReturnProductsInRequestV2.  # noqa: E501

        refunded amount for entire order (money)  # noqa: E501

        :return: The return_amount of this ReturnProductsInRequestV2.  # noqa: E501
        :rtype: float
        """
        return self._return_amount

    @return_amount.setter
    def return_amount(self, return_amount):
        """Sets the return_amount of this ReturnProductsInRequestV2.

        refunded amount for entire order (money)  # noqa: E501

        :param return_amount: The return_amount of this ReturnProductsInRequestV2.  # noqa: E501
        :type: float
        """
        if return_amount is None:
            raise ValueError("Invalid value for `return_amount`, must not be `None`")  # noqa: E501

        self._return_amount = return_amount

    @property
    def new_total_amount(self):
        """Gets the new_total_amount of this ReturnProductsInRequestV2.  # noqa: E501

        new order cost (money)  # noqa: E501

        :return: The new_total_amount of this ReturnProductsInRequestV2.  # noqa: E501
        :rtype: float
        """
        return self._new_total_amount

    @new_total_amount.setter
    def new_total_amount(self, new_total_amount):
        """Sets the new_total_amount of this ReturnProductsInRequestV2.

        new order cost (money)  # noqa: E501

        :param new_total_amount: The new_total_amount of this ReturnProductsInRequestV2.  # noqa: E501
        :type: float
        """
        if new_total_amount is None:
            raise ValueError("Invalid value for `new_total_amount`, must not be `None`")  # noqa: E501

        self._new_total_amount = new_total_amount

    @property
    def reason(self):
        """Gets the reason of this ReturnProductsInRequestV2.  # noqa: E501


        :return: The reason of this ReturnProductsInRequestV2.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this ReturnProductsInRequestV2.


        :param reason: The reason of this ReturnProductsInRequestV2.  # noqa: E501
        :type: str
        """
        if reason is None:
            raise ValueError("Invalid value for `reason`, must not be `None`")  # noqa: E501

        self._reason = reason

    @property
    def cancel_code(self):
        """Gets the cancel_code of this ReturnProductsInRequestV2.  # noqa: E501


        :return: The cancel_code of this ReturnProductsInRequestV2.  # noqa: E501
        :rtype: OrderCancelCodeEnum
        """
        return self._cancel_code

    @cancel_code.setter
    def cancel_code(self, cancel_code):
        """Sets the cancel_code of this ReturnProductsInRequestV2.


        :param cancel_code: The cancel_code of this ReturnProductsInRequestV2.  # noqa: E501
        :type: OrderCancelCodeEnum
        """

        self._cancel_code = cancel_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReturnProductsInRequestV2, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReturnProductsInRequestV2):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
