# coding: utf-8

"""
    Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WorkTimesUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'regular': 'list[RegularSchedule]',
        'special': 'list[SpecialSchedule]'
    }

    attribute_map = {
        'regular': 'regular',
        'special': 'special'
    }

    def __init__(self, regular=None, special=None):  # noqa: E501
        """WorkTimesUpdate - a model defined in Swagger"""  # noqa: E501
        self._regular = None
        self._special = None
        self.discriminator = None
        if regular is not None:
            self.regular = regular
        if special is not None:
            self.special = special

    @property
    def regular(self):
        """Gets the regular of this WorkTimesUpdate.  # noqa: E501


        :return: The regular of this WorkTimesUpdate.  # noqa: E501
        :rtype: list[RegularSchedule]
        """
        return self._regular

    @regular.setter
    def regular(self, regular):
        """Sets the regular of this WorkTimesUpdate.


        :param regular: The regular of this WorkTimesUpdate.  # noqa: E501
        :type: list[RegularSchedule]
        """

        self._regular = regular

    @property
    def special(self):
        """Gets the special of this WorkTimesUpdate.  # noqa: E501


        :return: The special of this WorkTimesUpdate.  # noqa: E501
        :rtype: list[SpecialSchedule]
        """
        return self._special

    @special.setter
    def special(self, special):
        """Sets the special of this WorkTimesUpdate.


        :param special: The special of this WorkTimesUpdate.  # noqa: E501
        :type: list[SpecialSchedule]
        """

        self._special = special

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkTimesUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkTimesUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
